### ISSUE TITLE
OpenSky Live Online Errors - v0.94.190303 Public Beta - Release Candidate 2

### ISSUE THREAD

**Issue by joshoram80** [TwinFan/LiveTraffic#119]
LiveTraffic 1551698426.1 ERROR src\LTChannel.cpp:433/FetchAllData: OpenSky Live Online: Could not get network data: 35 - schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

Spammed with red error messages in X-Plane, then both OpenSky Sources are disabled. I've had this issue since I started trying LiveTraffic quite a few version back, in XP 11.20, Now using 11.32 and the latest LT version, still the same error.

Bug previously identified in Error #71 and fix applied. Not working on my system though.

**Comment by TwinFan** [comment]
The error message in this case is slightly different:
```
35 - schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
```
in #71 it was
```
schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
```
Made the test for this error more generic. Was so far a check for the error number 0x80092012. Is now a test for the text "revocation".

Awaiting user's feedback if that now avoids the issue.

**Comment by TwinFan** [comment]
User reported to receive data now, but didn’t yet confirm expected message 
```
Querying revocation list failed - have set CURLSSLOPT_NO_REVOKE and am trying again
```
.
