### ISSUE TITLE
Aircraft Parking

### ISSUE THREAD

**Issue by deevilius** [TwinFan/LiveTraffic#124]
**Current Situation / Problem**
If aircrafts are displayed taxiing to the gate, they disappear after a while.
All gates are empty all the time.

**Suggested Solution**
When LiveTraffic is starting, fill a percentage of parking spots with ai traffic, for example 30%.
If i understand correctly airport creators can define which airline uses which gates -https://developer.x-plane.com/?article=guide-to-ramp-starts 

If a live aircraft is taxiing into a gate it should stay there parked at this gate. 
If the gate is already populated just despawn the old one.
The planes could "snap" to the parking position like static aircraft do.

This idea would be possible with the integration of RealTraffic.

**Alternatives**
-

**Benefits**
This would enhance the experience a lot. 
The airport gates are totaly empty now, and x-planes static parked aircraft are total nonsense. 
If i would sit for like an hour for example at an airport, a plane comes in, parks at a gate, stays there and 30 min later, the exact same plane is again pushing back. 

**Additional context**
In the future it would be possible to save which aircraft is parking at which parking position at a given time and day. So it would be possible to spawn exactly the right parked aircraft (or predict the right aircraft). For example 5:30 a.m. a Lufhansa A320 is depearting gate A20 in EDDF and i fire up x-plane at 5:20 a.m. then livetraffic could park a Lufthansa A320 at gate A20.

**Comment by TwinFan** [comment]
I have already stated at other places that I am not into taxiing simulation...and that includes parking. LiveTraffic is that: live traffic.
If at any time in the future there is live information available which aircrafts is parking right now at which gate, then we are talking. 'til then...I won't do it. But remember...it's open source.
