### ISSUE TITLE
Opensky network missing Australian (South Australia and Northern Territory) data.

### ISSUE THREAD

**Issue by scozz76** [TwinFan/LiveTraffic#134]
Opensky network missing Australian (South Australia and Northern Territory) data.

Since Early April this data has been missing.

Is there another source that can be used?

**Comment by TwinFan** [comment]
The [available channels and their requirements](https://twinfan.gitbook.io/livetraffic/introduction/features#live-flight-data-channels) are documented: OpenSky, ADSBEx, RealTraffic.
You may want to check the [OpenSky community forum](https://opensky-network.org/forum/index), maybe they have a view on the missing data. Reading is possible even without registration, and registration is free.
Closed, as this is not a LiveTraffic software issue.

**Comment by scozz76** [comment]
My question was regarding another source - I've been through their forums.

**Comment by scozz76** [comment]
> 
> 
> The [available channels and their requirements](https://twinfan.gitbook.io/livetraffic/introduction/features#live-flight-data-channels) are documented: OpenSky, ADSBEx, RealTraffic.
> You may want to check the [OpenSky community forum](https://opensky-network.org/forum/index), maybe they have a view on the missing data. Reading is possible even without registration, and registration is free.
> Closed, as this is not a LiveTraffic software issue.

My question was regarding another source - I've been through their forums.
