### ISSUE TITLE
teo

### ISSUE THREAD

**Issue by teodomiromalaquias** [TwinFan/LiveTraffic#154]
**Current Situation / Problem**
What does the current situation, processing, behaviour, problem look like?

**Suggested Solution**

**Alternatives**

**Benefits**
Why do you think an enhancement is necessary / beneficial?
Why should anyone invest the effort of implementing and testing it ;) ?

**Additional context**
Add any other context like log file/extract or screenshots about the feature request here.

**Comment by TwinFan** [comment]
Just the template text and no update...obviously a mistake. Closed.
