### ISSUE TITLE
FR24

### ISSUE THREAD

**Issue by jaapcammeraat** [TwinFan/LiveTraffic#157]
The free public website is free to use for everyone.
When you're looking in there webpagecode you can find this URL:
https://data-live.flightradar24.com/zones/fcgi/feed.js?bounds=52.62,51.92,3.47,5.40&faa=1&satellite=1&mlat=1&flarm=1&adsb=1&gnd=1&air=1&vehicles=1&estimated=1&maxage=14400&gliders=1&stats=1

My wish for LT is using FR24 because of the more accurate and complete aircraftdata also on the ground.

If that is not possible, please make an option to load a textfile every 'few' seconds with a special format, so that 'we' can create an app to download the FR24 data and put it in this textfile of LT.

**Comment by TwinFan** [comment]
"Possible" is not the same as "free"! I respect [terms and conditions](https://www.flightradar24.com/terms-and-conditions) (which only allows to use "services" like apps but not raw data), as I expect everybody to respect my license conditions. It's not that I didn't try, you might already be aware of the [FR24 FAQ](https://twinfan.gitbook.io/livetraffic/reference/faq#can-you-support-flightradar24-as-a-channel):

> Can you support Flightradar24 as a channel?
Technically yes, I can. But legally I am not allowed, sorry. I've checked with FR24 support. They do not yet allow using their data outside their own applications. Maybe, so their answer, they will provide a (paid) model in the future...maybe not.

**Comment by jaapcammeraat** [comment]
Yeah you're right! I've also contacted them twice. They are not willing to help a gamer :-)

**Comment by jaapcammeraat** [comment]
Well, can you provide a textfile-system so that I can input my data of my own ADB receiver into LT?
