### ISSUE TITLE
File with ADS-B info

### ISSUE THREAD

**Issue by jaapcammeraat** [TwinFan/LiveTraffic#159]
I want to use my own ADS-B data as a source for LT.
My wish for LT is a kind of file which LT is loading and deleting after use, with the flightdata I will provide with my own receivers.

**Comment by TwinFan** [comment]
Won’t do. See (here)[https://twinfan.gitbook.io/livetraffic/reference/faq#can-i-use-the-data-of-my-local-ads-b-receiver] why.
