### ISSUE TITLE
Aircrafts landing like animals 

### ISSUE THREAD

**Issue by DemonRem** [TwinFan/LiveTraffic#161]
1st aircraft landing on runway in some airport they get in to the runway i mean they land under the runway

2nd the aircraft preform flare to early and in sharp state.

**Comment by TwinFan** [comment]
Understand [design approach and limitations](https://twinfan.gitbook.io/livetraffic/introduction/limitations). Read about [how support works](https://twinfan.gitbook.io/livetraffic/reference/help-and-support), especially [what is a bug and what not](https://twinfan.gitbook.io/livetraffic/reference/help-and-support#bugs-defects-problems-issues-suggestions). 

In case of reproducible problems please go with a comprehensible problem description to the [LiveTraffic support forum](https://forums.x-plane.org/index.php?/forums/topic/174691-if-you-want-support-contains-template/).
