### ISSUE TITLE
Ground Handling

### ISSUE THREAD

**Issue by DemonRem** [TwinFan/LiveTraffic#162]
Ai Aircraft taxi when i front him he keep taxi on me.

**Comment by TwinFan** [comment]
Understand [limitations](https://twinfan.gitbook.io/livetraffic/introduction/limitations#implications-on-simulated-aircraft), which explicitly state

> Live aircraft will ignore your own plane.
Live aircraft will be where reality puts them regardless of your plane's position. They simply fly or drive through you if you are in the way. That can look funny if you are stopping short at the beginning of the active departure runway and a A380 performs its take-off roll through you.
You may, however, [impersonate an existing plane](https://twinfan.gitbook.io/livetraffic/using-lt/aircraft-information-window/hide-and-impersonate-aircrafts#impersonate-an-aircraft) and take over its queue position!
