### ISSUE TITLE
XPlane crash on start 

### ISSUE THREAD

**Issue by alessio0012** [TwinFan/LiveTraffic#163]
Hello everyone, 
so when I start up X plane 10 with the LiveTraffic installed it just crashes. It used to work many version back.
Thank you for taking your time.

[Log.txt](https://github.com/TwinFan/LiveTraffic/files/3778118/Log.txt)

**Comment by TwinFan** [comment]
The first error occurring is (consistent with your wording „many versions back“):

```
LiveTraffic 1572255555.8 ERROR src\DataRefs.cpp:1611/LoadConfigFile: Config file 'C:\Users/liamsomers/Documents/X-Plane 10/Output/preferences/LiveTraffic.prf' first line: Unsupported format or version: 
Failed: C:\Users/liamsomers/Documents/X-Plane 10/Resources/plugins/LiveTraffic/64/win.xpl. (The plugin refused to start by returning 0 from XPluginStart.)
```

So LiveTraffic‘s config file is unreadable. Should not happen, also not after upgrades, but only once leaving original beta phase. So maybe your upgrade is skipping too many version.

Solution is simple: Remove `X-Plane 10/Output/preferences/LiveTraffic.prf` (or move it someplace else if you want to look up settings) and LiveTRaffic will create a new one.

(Having said so, please also make sure that other configuration files in the `LiveTraffic` plugin folder are correctly updated, like `FlightModels.txt`, `related.txt`...basically _everything_ in the installation archive.)

The next LiveTraffic message at the end of the log file is
```LiveTraffic 1572255822.8 FATAL src\LTMain.cpp:523/LTMainShowAircraft: ASSERT FAILED: dataRefs.pluginState >= STATE_ENABLED```
Given that the plugin didn’t even initialize the message as such is understandable...but the plugin should never actually even _try_ to display aircraft. Not sure why it tries...but I wouldn’t go into too much details here. Fix the startup...and this follow-up problem will not happen.
This is LiveTraffic‘s exception handler, which usually tries _avoiding_ a fatal crash. But certainly you can never be sure...

The actual X-Plane crash is _not_ in LiveTraffic:
```
--=={This application has crashed because of the plugin: PythonInterface}==--
```
So I can‘t analyze the exact crash location. It might however be triggered by a LiveTraffic action/error, so let‘s fix the startup and I‘m sure it works again.

**Comment by TwinFan** [comment]
Closed, no reaction, assuming above tip worked.
