### ISSUE TITLE
No Turbo Propeller Rotation on approach

### ISSUE THREAD

**Issue by fkolbe** [TwinFan/LiveTraffic#167]
In X-plane 11.41 when viewing a turbo prop like a dash 8/q400 on approach the props are at a standstill. I’m not sure if this is a Live Traffic or other issue.  They’re not rotating which looks quite odd. 

To reproduce this:
1 open flight in XP11.41;
2. Using the pop out window choose a turbo-prop like Dash8/Q400
3.place checkmark in the camera box
4. Observe no rotating prop. 

Thank you.

**Comment by TwinFan** [comment]
[See documentation](https://twinfan.gitbook.io/livetraffic/setup/installation/csl2xsb). Depends on CSL package. Bluebell package can be converted. After conversion, the Q400 included in the Bluebell package does rotate props.
