### ISSUE TITLE
Car identification enhancements (call sign, taxiway)

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#186]
**Current Situation / Problem**
Identification of ground vehicles currently depends on some combination of odd values per channel. Only OpenSky has a clear identifying text for ground vehicles, but even that is not properly set of the transponder code of the vehicle is unknown. And ground vehicles are very often just not tracked in aircraft database...they aren‘t aircraft in the end.

Many vehicles, which the human eye can easily identify as cars, are hence still displayed with the default aircraft instead as a clear identification as car fails

**Suggested Solution**
- [x] Call signs: Some call sign patterns strongly indicate ground vehicles:
    - [[:alpha:]]{2}[[:digit:]]{1,2}
       Ie. 2 letters, 1-2 digits (that is not fail proof, but most of them are cars. Airlines use 3 letter callsigns.
    - [[:alpha:]]{1}[[:digit:]]{1,3}
    - TUG[[:digit:]]*
    - AIR[[:digit:]]*
    - AGL[[:digit:]]*
    - SAFE[[:digit:]]*
    - MEDIC[[:digit:]]*
    - ARFF[[:digit:]]*
    - MICC (often seen at OMDB)
    - [x] Make list configurable, can probably be included in `FlightModels.prf` as a special section. That file has other regex patterns already
- [x] Operator contains the word „airport“

**Benefits**
More vehicles properly identified

**Comment by voipmeister** [comment]
Ground vehicules at VHHH take this form: 
- [[:alpha:]]{2}[[:digit:]]{1,2}
- SW5
- AF14

They also drive around on taxiways a lot and I have also seen them on runways, which doesn't help in this case :-)
