### ISSUE TITLE
Prioritize OpenSky master data over all other

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#204]
**Current Situation / Problem**
Maintaining aircraft master data (most importantly: type and operator) is a huge effort. All tracking data networks have some kind of database to keep track of this. But they offer different reading and writing access to it.

OpenSky has the most transparent and open model:
- Master data can be requested completely independent from tracking data for any aircraft, which is why "OpenSky Master Data" appears as separate channel in LiveTraffic.
- The [aircraft database](https://opensky-network.org/aircraft-database) can be update by any registered (free!) OpenSky user, so any mistake can be corrected immediately. The LiveTraffic documentation makes mention of this fact in various places.

LiveTraffic does use OpenSky master data to enrich any channel's tracking data, but currently only if the tracking data channel does not deliver master data itself.

The issue now is that in some situation for example ADSBEx delivers wrong master data as part of its tracking data. LiveTraffic, however, does not currently check with OpenSky as it received master data already and will then use that wrong data from ADSBEx. But we cannot easily correct ADSBEx's data.

**Suggested Solution**
Give OpenSky Master priority:
Always check with OpenSky Master data for aircraft master data and use that data when available.
Only when no OpenSky Master data is available use the master data delivered with the tracking data.

If then some data is wrong it can easily be changed [at the source](https://opensky-network.org/aircraft-database) to the benefit of the entire community.

**Benefits**
Controlled aircraft master data, leading to better model and livery matching.

**Comment by voipmeister** [comment]
I'd like to suggest the addition of a (by default disabled) separate logfile for incomplete OpenSky data, so we as the community may add missing info that was spotted by LT.
