### ISSUE TITLE
Error building in Visual Studio

### ISSUE THREAD

**Issue by veetine** [TwinFan/LiveTraffic#234]
C1047 The object or library file "Lib\XMMP2\win\ xpmp2. Lib "is created using a different compiler version than other objects such as" build\x64\Release\base64.obj "; Use the same compiler to generate all objects and libraries
![image](https://user-images.githubusercontent.com/9909246/164969725-893a4751-ceb9-4bf9-85c7-b5ca31e28518.png)
Look forward to your reply! Thank you

**Comment by TwinFan** [comment]
The uploaded version of `XPMP2.lib` has been built with GitHub actions, ie. using GitHub's software, in this case Visual Studio Enterprise 2022. This way, also LiveTraffic can be built with GitHub actions automatically.

`base64.obj` has been build by yourself (as all the `.obj` files) when building the project. If you use an older version of Visual Studio, then it may not be able to process the provided `XPMP2.lib`.

_Solution:_ You can either use the same version of Visual Studio (though I am not sure if Visual Studio Community 2022 will work but it is worth a try). Or you can also build [XPMP2](https://github.com/TwinFan/XPMP2) yourself and replace `XPMP2.lib`. The latter is what I do when building with VS.

I shall add a note to this fact into LiveTraffic's `README.md` file.
