### ISSUE TITLE
User Login and rate limit handling for Opensky

### ISSUE THREAD

**Issue by fabland** [TwinFan/LiveTraffic#237]
## Describe the bug
The Opensky API integration doesn't handle the response case 429 (Too Many Requests) correctly. This can occur due to the rate limit depending on how the API is used: https://openskynetwork.github.io/opensky-api/rest.html#limitations

## To Reproduce
1. Enable the Opensky integration
2. With standard settings of 1 request every 20 seconds the limit should be reached after around 30 min

## Expected behavior
The Opensky API calls should stop or back-off and not do any additional request to the API until x seconds mentioned in header pass. 

Additionally to allow users to use the live Opensky API longer it would be good to allow authenticated requests to the Opensky API. For this the username and password needs to be configurable in the settings and should be passed in the request as auth header. This would allow the API to be user 10x longer for registered Opensky users.

**Comment by TwinFan** [comment]
…as discussed in [this support thread](https://forums.x-plane.org/index.php?/forums/topic/269007-keep-getting-a-fatal-error/&do=findComment&comment=2377576).
