### ISSUE TITLE
X-CSL contains a trojan malware as reported by Virus Total

### ISSUE THREAD

**Issue by confile** [TwinFan/LiveTraffic#256]
X-CSL contains a trojan malware as reported by Virus Total

![pc-flight1](https://github.com/TwinFan/LiveTraffic/assets/64265/6ab27065-5be6-4a24-97e3-b460fb5b9550)

**Comment by TwinFan** [comment]
Well, thanks for noting, but what do you expect me to do? Yes, I refer to X-CSL for planes, but X-CSL is not my product.

**Comment by confile** [comment]
You link to an archive that contains malware. That should be not what you want.
