### ISSUE TITLE
No pressure altitude correcton above transition altitude

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#269]
## Describe the bug
Planes at high altitude are effectively flying at the wrong altitude. They don't keep to their flight levels.
This is due to _all_ altitudes being correct for barometric pressure, which is essential closer to ground so they keep their runway approaches and touch down at the beginning of a runway, but wrong above transition altitude.

## To Reproduce
Cruise at high altitude, like FL320 and potentially watch traffic in the opposite direction come towards you at your altitude.

## Expected behavior
Planes are expected to fly at their real-world altitudes.

## Technical Info
 - OS: any
 - X-Plane version: any
 - LiveTraffic version: since ever

## Reference
[Raised in the support forum](https://forums.x-plane.org/index.php?/forums/topic/309819-altitude-calibration/).

## Background
Altitude data collected from the tracking sources is barometric altitude. (Or it turned out that using the barometric altitude is the more reliable data as this comes straight from the ADS-B senders. Some sources also provide a converted value labelled GPS altitude, but it turned out to be very unreliable.)

LiveTraffic now needs to convert this value in a physical altitude the same way as an aircraft. In an aircraft the QNH value is to be entered into the altimeter. And the same way LiveTraffic corrects the barometric altitude using the area's QNH value, which is why LiveTraffic processes weather information as seen in its [Status Window](https://twinfan.gitbook.io/livetraffic/using-lt/info-list-window/status-about).

However, after passing transition altitude, real-world planes change the altimeter to standard pressure, ie. pressure altitude at high altitudes is no longer corrected for area air pressure but used directly to have a common ground during cruising across large areas.

That's what's missing in LiveTraffic: LiveTraffic always converts _all_ altitude readings. But it must not do so for planes flying above transition altitude. The tricky thing is that transition altitude is not universal. It can be different per airport or region.
To keep things simple let's assume that transition altitude is 10,000ft, ie. for any altitude reading above 10,000 LiveTraffic shall no longer apply altimeter correction.

**Comment by 172MC** [comment]
“To keep things simple”
Well, things ARE simple in the US and Canada, 18,000ft is the transition altitude everywhere there. Any way to have LT use that there and 10,000ft for everywhere else?

**Comment by TwinFan** [comment]
And there it goes...bye bye simplicity ;-)

**Comment by 172MC** [comment]
Considering that nobody even noticed the issue for years, I now regret my comment and agree that you should keep it really simple: 10,000ft transition altitude everywhere is fine.
All the best to you, TwinFan.

**Comment by TwinFan** [comment]
Don't worry...I'm not going to spend sleepless nights over the issue...and there is no hotfix coming up for it either :-)
