### ISSUE TITLE
Incorporate Traffic from the SayIntentions FlightTracker

### ISSUE THREAD

**Issue by daijoubu** [TwinFan/LiveTraffic#274]
Please add the SayIntentions flight tracker as a data source that LiveTraffic can inject into the sim.  Brian would be willing work with you on a datafeed for LiveTraffic to consume.

## Benefits
This will allow XP12 SayIntentions users to see the traffic they hear on ATC.

**Comment by TwinFan** [comment]
Then I'd need contact info for Brian, or he jumps on this issue.

What LiveTraffic essentially needs is per aircraft:
- unique Numerical or hex id (per design this is the ADS-B transmitter's id, but anything unique will do)
- Latitude, Longitude, 5 decimals
- Altitude in ft or meter above sea level 
- Unix or Java timestamp when this position was valid

The more the merrier as display will become more accurate:
- aircraft type code (ICAO doc8643)
- true heading in degrees 
- call sign

[Read about livery matching](https://twinfan.gitbook.io/livetraffic/reference/faq#how-does-it-work). There is no mechanism to "upload" liveries. It all depends on what individual users have installed locally. (Keep in mind that LiveTraffic was designed to display real life traffic.)

LiveTraffic needs a URL that accepts a location (lat/lon) as a center position with a fixed or variable radius as query parameters, or alternatively two locations defining a search rectangle. The result shall be all aircraft in the range defined by the parameters. Format can be just CSV or JSON.

There is no LiveTraffic "standard" as LiveTraffic needed to adapt to available tracking data sources. For inspiration look at the [ADSBEx](Data/ADSB/adsb.fi/adsb.fi.json) format (already used by two channels) or [FSCharter](https://github.com/TwinFan/LiveTraffic/tree/master/Data/FSCharter) (serving a similar purpose, also defines things like login if you want to restrict usage to authenticated users, or a slug to provide a link to the specific flight on your platform). But really...any well defined format will do.

**Comment by daijoubu** [comment]
Thanks for the response!  I saw in the SI discord that another user Korey spoke with you and was going to have Brian reach out to you.  I got the idea from your support of FSCharter.

**Comment by TwinFan** [comment]
I am not aware that I would have been contacted in this matter of an interface to SayIntentions, so there's no progress. Communication should be exactly _here_.

**Comment by daijoubu** [comment]
It sounds like Brian is pretty busy but they have a publicly available list of all active flights.  Looking at the data it feels like something I could build using one of the existing input channels as a template.

The URL is:
https://lambda.sayintentions.ai/tracker/map
It returns an array of all active flights on the network with this data about each flight:
"flight_id":813308,
"displayname":"Jon174",
"altitude_agl":0,
"origin":"",
"final_destination":"",
"callsign":"LearJet-Nine-Eight-Six-Sierra-Alpha",
"lat":41.0406795141418,
"lon":-81.4625090279334,
"tail_number":"986SA",
"heading":92,"altitude":1055,
"airspeed":0,
"aircraft_type":"jet",
"aircraft_icao":null,
"flight_icao":null,
"flight_plan":null,
"flight_plan_origin":null,
"flight_plan_destination":null,
"flight_rules":"VFR",
"flight_plan_route":null,
"atc_title":"LEARJET 35A N986SA PMSGTN750+RADAR",
"simbrief_model":null,
"flight_type":"GA",
"landing_rate":null,
"crisis_triggered":0,
"crisis_id":null,
"crisis_description":null,
"partner":1

**Comment by TwinFan** [comment]
That's great, I can easily work with that!

At some point in time, before publishing the new version with this channel in, I'd like to have a confirmation by Brian that using this endpoint is OK for him. Adds a tiny bit more load on his server(s). (I request this confirmation for every source I'm using.)

But in the meantime I can start implementation. Shouldn't take too long, looks like good data. Looking at [the official map](https://tracker.sayintentions.ai/) it also looks like data updates often enough.

Just one word of caution, also from looking at the map: Don't get too enthusiastic about the effect you'll have in X-Plane: You will rarely be seeing any other SayIntentions plane in the sim. It is not that busy (yet). You can't really see a plane more than, well, 3 miles out in good weather. And there aren't that many in any given 3nm radius except for at a few airports.

**Comment by daijoubu** [comment]
Wonderful, thank you!  I understand about the scarcity of traffic.  They have a multiplayer feature with the ATC that lets you hear other aircraft on the same frequency as you.  This will complement that, letting us see the other traffic that we can hear.

**Comment by brianshell** [comment]
I'm the developer of SayIntentions -- you have permission to use the data-feed. HOWEVER, I would like an open line of communication in case we have to make any adjustments. I'm 'brianshell' on Discord.  Thanks!!!!!

**Comment by TwinFan** [comment]
@daijoubu , you may want to try this preview of v4.1, just copy the provided files over those in your installation:
[LiveTraffic_410.zip](https://github.com/user-attachments/files/17758586/LiveTraffic_410.zip)
Beta versions like this preview expire after one month. So do update from X-Plane.org once I publish officially.

I've made [the documentation already public](https://twinfan.gitbook.io/livetraffic/setup/installation/sayintentions).

Any feedback appreciated.

**Comment by daijoubu** [comment]
@TwinFan I can see aircraft in the sim and track them through flight, but the aircraft info pages are not showing any details.  Is this a limitation with SI or am I having an issue?  
![image](https://github.com/user-attachments/assets/5d29f1a2-8c52-474e-bbdb-5aba669c1295)

**Comment by TwinFan** [comment]
Good catch! I had used the Info Wnd in the "AUTO" mode only, ie. pointed with the camera at a visible plane (like with the camera button), and that had worked.

My intention to show the flight ids right aligned with proper amount of leading spaces went wrong...leading spaces get lost in some processing in other places. So no more leading spaces, just the plain number, and then that works:
[LiveTraffic_410.zip](https://github.com/user-attachments/files/17779124/LiveTraffic_410.zip)

**Comment by firewiz1976** [comment]
Can i test it?

**Comment by daijoubu** [comment]
Looks good!  The pop out info screens are working well, thank you!

**Comment by daijoubu** [comment]
@TwinFan If you reach out to Brian he'd like to thank you with a 1 yr subscription for your efforts.

**Comment by TwinFan** [comment]
Appreciated, really, and maybe I even try once or twice just to see how mature AI is by now...

I had tried reaching out to @brianshell on Discord already by sending a Friend Request (I'm TwinFan there) some days ago as he asked for a channel to discuss changes when they occur...have yet to hear back. I've also joined the SI server, but I'm a rather passive listener on Discord...
