### ISSUE TITLE
Make CSL paths configurable

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#42]
**Current Situation / Problem**
Currently, LiveTraffic looks into the hard-coded path `plugins/XSquawkBox/Resources/CSL` to find CSL packages. If XSB is installed elsewhere that will fail.
Checking X-IvAp paths is not even implemented yet.

**Suggested Solution**
Walk all plugins, search for "Resources/CSL" and just take that.
Make multiple calls to `XPMPLoadCSLPackage` to load additional CSL directories if there is more than one.

**Benefits**
Independence if individual user's setup.

** Still to do **
- [ ] Settings UI tab with 5 or so edit fields for the paths, and checkboxes for enable/disable
- [ ]   ...and maybe a 'Load' button to load a package on demand
- [ ]   LTMainInit: Ability to startup and show the settings UI even if CSL init failed

**Comment by 172MC** [comment]
"Make multiple calls to XPMPLoadCSLPackage to load additional CSL directories if there is more than one."

What if they overlap, possibly with conflicts (same ICAO, different models/liveries)

**Comment by TwinFan** [comment]
I would test that and see what the multiplayer library makes of it. Anyway...there are more issues than that. From your logs, e.g., I read that CSL models are also installed in folder not called "Resources/CSL". I would miss them.

So I am unsure how to allow for a very simple install also for beginners on the one hand, while on the others allow power users like you to fine-tune settings.

Just an idea I had: LT writes out the directories found into the LiveTraffic.prf. A power user can edit that file and specify exactly which directories to consider and which not. And the beginner would just ignore all that and LT would find something somewhere...

And maybe I just make things too complicated and should simply demand a CSL package in _my_ directory like all other plugins do...it's just 3.5 GB in the end :)

**Comment by TwinFan** [comment]
Yea...I gonna roll back that complexity. The only thing I gonna offer is to configure one (maybe five) paths to CSL directories. And for installation and startup purposes LiveTraffic will only check in its own Resources/CSL. Full stop.

**Comment by TwinFan** [comment]
- [ ] Settings UI tab with 5 or so edit fields for the paths, and checkboxes for enable/disable
- [ ] ...and maybe a 'Load' button to load a package on demand
- [ ] `LTMainInit`: Ability to startup and show the settings UI even if CSL init failed
