### ISSUE TITLE
Send traffic to ForeFlight

### ISSUE THREAD

**Issue by 172MC** [TwinFan/LiveTraffic#47]
This is probably way too early in the development to make this suggestion, but …

X-Plane can connect to Foreflight and PilotEdge sends its traffic to ForeFlight, which shows it (if traffic is enabled in Foreflight). PE has a .ini file containing only the local network IP address of the iPad/iPhone on which ForeFlight Mobile is running.

Feature request: would LT do the same please?

-------
Can do.

Todo list:
- [x] [ForeFlight documentation](https://www.foreflight.com/support/network-gps/)
- [x] Configuration for
    - [x] Sending user plane's data
    - [x] Sending live traffic
    - [x] port
- [x] UI Settings for the same
- [x] Broadcast send capability
- [x] Thread for sending (standard 10-20s call isn't sufficient, Foreflight requires updates more often)
    - [x] User's plane GPS
    - [x] User's plane attitude
    - [x] Live traffic planes
- [x] Documentation (warning: if RealTraffic broadcasts, it always also broadcasts Foreflight data on 49002! So parallel operations is somewhat difficult)

**Comment by TwinFan** [comment]
With the RealTraffic integration (#65) I came to learn the ForeFlight format, which is also send by RealTraffic. And it is really simple.
And now I also found [official developer's documentation by ForeFlight](https://www.foreflight.com/support/network-gps/).
