### ISSUE TITLE
AC sliding and rocketing

### ISSUE THREAD

**Issue by CloudSkimmer** [TwinFan/LiveTraffic#48]
**Describe the bug**
A clear and concise description of what the bug is: What's wrong?
Some ac slide sideways across a runway to line up or while landing/taxiing. Others as we have discussed, have been rocketing up and down (_yoyo effect_)

**To Reproduce**
Just start xplane on a particular busy runway

1. Location: LSZH RW 28
2. Tuesday, Dec 4th, approx 4pm (1600)
3. Usually an a319 or a320
4. A Log.txt file with log level (Settings/Advanced) set to 'Debug' **INCLUDED**
5. I will try to upload a video (4min) oops! NOT POSSIBLE HERE..will try YouTube or?? _Ask me if you'd like me to package and send it to you in a zip_ 👍 

**Expected behavior**
explained already

**Screenshots**
INCLUDED ;) 

**Technical Info:**
 - OS: Windows 10 64 Pro
 - X-Plane version: 11:30b6
 - LiveTraffic version: 0.81.20181202

**In photos 1,2 and 3 you'll see the sliding sequence:**

[Log.txt](https://github.com/TwinFan/LiveTraffic/files/2644810/Log.txt)
![milviz cessna 310r_1](https://user-images.githubusercontent.com/45555040/49455628-bf130180-f7e7-11e8-8424-485ecb35db3c.png)
![milviz cessna 310r_2](https://user-images.githubusercontent.com/45555040/49455644-c4704c00-f7e7-11e8-8556-92fd14130b3c.png)
![milviz cessna 310r_3](https://user-images.githubusercontent.com/45555040/49455654-c89c6980-f7e7-11e8-8d84-61c49fa696fc.png)

**Log.txt**
Attach your Log.txt file, if reproducible then please reproduce with log level (Settings/Advanced) set to 'Debug' first.

**Comment by TwinFan** [comment]
A video would be of no help. A network raw data log is the best way for analysis, see [Tips for Testers](https://twinfan.gitbook.io/livetraffic/tips-on-testing#general-setup).

Also, enable "Debug: Log a/c position". Then, once you see a a/c behaving weird open an a/c info window for that aircraft. It's computed positions is logged to Log.txt.

**Comment by TwinFan** [comment]
While analysing raw flight data for #57 I came across candidates for rocket planes. OpenSky seems to send lots of `null` messages, which LT so far interprets as `0`. See [here](https://github.com/TwinFan/LiveTraffic/issues/57#issuecomment-447311005).

**Comment by TwinFan** [comment]
Analysis consolidated in #57.
