### ISSUE TITLE
cant find CSL if path contains spaces

### ISSUE THREAD

**Issue by MuellerPatrick** [TwinFan/LiveTraffic#56]
**Describe the bug**
If I put a CSL path in the prf which contains spaces, the path isnt parsed correct.
Only the part after the space is used for building the path to the CSL.

**To Reproduce**
path is /resources/plugins/X-Ivap Resources/csl
in log.txt you can see the csl path          Resources/csl 

**Technical Info:**
 - OS: Win10
 - X-Plane version: 11.30b7
 - LiveTraffic version: 0.83

________
KosFlyer

**Comment by TwinFan** [comment]
Yea, confirmed...that implementation was a bit too simplistic;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
