### ISSUE TITLE
360 on approach. plane lands 300ft above the ground.

### ISSUE THREAD

**Issue by MuellerPatrick** [TwinFan/LiveTraffic#58]
![lt_toohigh](https://user-images.githubusercontent.com/45783857/49933758-d5e2e380-fecc-11e8-804a-7c81b9042c52.png)
**Describe the bug**
Follow the plane 440053 on approach to malta.
short before the runway the plane does a 360 on place.
Then it lands ~300ft above the ground and taxi to gate ("in the air").

**Screenshots**
Is included.

**Technical Info:**
 - OS: Win10
 - X-Plane version: 11.30b7
 - LiveTraffic version: 0.83

**Log.txt**
Log is inluded.
[LTRawFD.log](https://github.com/TwinFan/LiveTraffic/files/2675614/LTRawFD.log)

LTRawFD is included
[Log.txt](https://github.com/TwinFan/LiveTraffic/files/2675612/Log.txt)

**Comment by TwinFan** [comment]
Also here: The planes appears in both OpenSky and ADS-B-Exchange streams. I could probably proof from the network raw data (thanks for attaching, that's really helpful!) that around touch down the data is not aligned perfectly...
But anyway: I need to put a stop on multiple channel usage...an intelligent stop, certainly, linked with #61.

**Comment by MuellerPatrick** [comment]
Yeah ok, its right, I checked all boxes for data deliveries that I can check :-D
I understand the problem that results in the doubled data. I switched to ADS-B only for now.

**Comment by TwinFan** [comment]
Analysis consolidated in #57.
