### ISSUE TITLE
Feature: Wake turbulence 

### ISSUE THREAD

**Issue by CloudSkimmer** [TwinFan/LiveTraffic#59]
Once everything is more or less squared away, what is the chance of simulated wake turbulence?  Just a thought

**Comment by TwinFan** [comment]
Quite unlikely...that would be a function of the plane in front of another.

**Comment by TwinFan** [comment]
XP12 will support a wake turbulence functionality, which LiveTraffic to a certain extend already supports by default without any change:
https://developer.x-plane.com/article/plugin-traffic-wake-turbulence/

Philipp posted a few preliminary screenshots in a [forum post](https://forums.x-plane.org/index.php?/forums/topic/262509-live-traffic-in-x-plane-12/).

For best support, XPMP2 will need to support a few more fields, which can drive the new `wake` datarefs to provide even more fine-grained wake.
