### ISSUE TITLE
Auto a/c info window: Show info on plane in front of me

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#62]
**Current Situation / Problem**
Entering an a/c id in the a/c info wnd is cumbersome. There is the idea of an aircraft list (#21), but here's another one:

**Suggested Solution**
For months already I was thinking about how I could ease entering the a/c id in the a/c info wnd....esepcially in a VR environment that's difficult.
But there is no functionality in XPlane to map a 2-D mouse click onto an object in 3-D space, so it is not possible to just click on such a multiplayer aircraft and let LT id it.

The idea is: Just display the information of the plane that is closest to the viewer in the direction of viewing...that shouldn't be too difficult to achieve.

**Benefits**
Automated info on the a/c in front of me.

**Comment by MuellerPatrick** [comment]
A window with a table of the (5) nearest aircraft is also interesting.

**Comment by TwinFan** [comment]
That's what #21 is about.

**Comment by MuellerPatrick** [comment]
checked

**Comment by TwinFan** [comment]
Implemented new menu entry for an auto-info wnd. Just entering "AUTO" in a standard info window has the same effect and switches to AUTO mode. Entering a key switches AUTO mode off. Window title says "(AUTO)" if so.
Follows the closest a/c in a +/- 20° degree range of camera view. Switches automatically when a better a/c comes into view.
