### ISSUE TITLE
New channel: "RealTraffic"

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#65]
**Current Situation / Problem**
[RealTraffic](http://www.inside.net/ss/realtraffic-for-psx/) is not yet supported. It is an affordable flight tracking data service already used by plugins for other simulators.

**Suggested Solution**
Support RealTraffic as data provider in LiveTraffic.

**Benefits**
Possibly better-quality data than the freeware provides we support at the moment.

**Additional context**
From their website it is unfortunately a bit unclear how they integrate with plugins. I've downloaded the "standalone" client and from its configuration it looks like data is broadcasted to an ip address/port, probably using UDP.

- [x] Contact Inside Systems about developer documentation.
- [x] Check if there is an affordable developer license. Not willing to pay full price during development of an open source plugin.
- [x] Decide if and how RealTraffic could be included into LiveTraffic to form Real LiveTraffic ;)
- [x] Devise a reasonable timestamp per UDP datagram...the msg doesn't have one!
- [x] Adjust received altitude by local pressure, requires also reading RT's weather messages
- [x] Ignore heading changes while stationary
- [x] Have RT connect to LT and report LT‘s position to RT
- [x] Deal with planes hovering along the runway after Final
- ~~Try to get RealTraffic to behave better with ForeFlight by injecting own position more often (might make device "PSX" appear consistently...which in turn would allow to switch if off)~~ Didn't work.

**Comment by darealgege** [comment]
Open Glider Network would be great also (it is great for GA)

**Comment by TwinFan** [comment]
Sent out first contact request to Inside Systems.

**Comment by TwinFan** [comment]
Received developer‘s documentation and a license...ready to go!

**Comment by TwinFan** [comment]
Can receive RealTraffic's UDP broadcast already:
```
LiveTraffic 1551823781.6 INFO  LTChannel.cpp:615/LTFlightDataShowAircraft: Requesting live flight data online...
LiveTraffic 1551823781.6 INFO  LTRealTraffic.cpp:93/SetStatus: RealTraffic network status changed to: Starting...
LiveTraffic 1551823790.8 DEBUG LTRealTraffic.cpp:257/ProcessRecvedWeatherData: Received Weather: {"ICAO": "KJFK","QNH": 2995, "METAR": "KJFK 052151Z 25016KT 10SM FEW050 FEW250 M01/M10 A2995 RMK AO2 WSHFT 2053 SLP140 T10061100", "NAME": "John F Kennedy International Airport", "IATA": "JFK","DISTNM": 0.1}
LiveTraffic 1551823790.9 INFO  LTRealTraffic.cpp:93/SetStatus: RealTraffic network status changed to: Connected passively
LiveTraffic 1551823790.9 DEBUG LTRealTraffic.cpp:251/ProcessRecvedTrafficData: Received Traffic: AITFC,531926181,41.0873,-75.1370,22975,0,1,114,457,DAL106,B712,N966AT,MSP,JFK
LiveTraffic 1551823790.9 DEBUG LTRealTraffic.cpp:251/ProcessRecvedTrafficData: Received Traffic: AITFC,531942684,40.6357,-73.7859,0,0,1,120,22,AAL2291,B738,N967NN,JFK,CLT
LiveTraffic 1551823790.9 DEBUG LTRealTraffic.cpp:251/ProcessRecvedTrafficData: Received Traffic: AITFC,531826949,40.6375,-73.7765,0,0,1,8,27,KAC117,B77W,9K-AOD,KWI,JFK
LiveTraffic 1551823790.9 DEBUG LTRealTraffic.cpp:251/ProcessRecvedTrafficData: Received Traffic: AITFC,531934590,40.8510,-74.0683,0,0,1,106,0,C25B,C25B,,,
LiveTraffic 1551823790.9 DEBUG LTRealTraffic.cpp:251/ProcessRecvedTrafficData: Received Traffic: AITFC,531922133,39.9217,-74.9885,2950,-64,1,256,171,AAL40
```

**Comment by TwinFan** [comment]
Detail and accuracy issues to work around:
- [ ] There is no real transponder id, i.e. the plane cannot be easily matched with traffic or data from other channels. The id in front seems to be some arbitrary id which increases over time. Need to find something to map the tail number back to transponder id as used in all other streams. Maybe the downloadable aircraft file (#7)

- [ ] There is no timestamp with the data. That‘s really bad! There is no info _when_ the position was valid. That badly affects speed calculations. So far, planes accelerate and decelerate over and over again over short distances. Looks really ugly. Only idea I have is to soften the effect by using a kind of moving average for timestamp so that speeds stay reasonable.

- [ ] The „airborne“ flag is always true. Detection if ground or not currently assumes „0,0,1“ or „0,0,0“ for altitude, VS and the airborne flag. Apparently, the local RealTraffic.app can reliably distinguish between ground and no ground but fails to pass on this info.

Answers by the developer to these queries are yet inconclusive. So I have to help myself.

**Comment by TwinFan** [comment]
Only remaining issue...but that is in the received data: For approaching planes I not so rarely do not receive an on-the-ground position but instead several repetitions of levelled position a few dozen feet above ground, only many many seconds later followed by an on-ground position. That makes the planes do a fly-over along the runway and either touch down at the end in a rush...or keep on moving ad infitum as the on-ground position is backward (180° turn), which is filtered out by data cleansing.

That looks ugly...but I've no idea as of yet how to identify that case. I would need a lot more look ahead buffer for doing so.

**Comment by deevilius** [comment]
I am really looking forward to the RealTraffic, integration. Use it with psxseecontraffic for over a year now in p3d and the data is much better. if you need help with testing or something like that, send me a message. you are doing a great job with this plugin!

**Comment by TwinFan** [comment]
With the above commit the main functionality is in. Except for the issue that sometimes approaching aircraft keep hovering over and along the runway (see comment before) it should work now.

**Comment by deevilius** [comment]
nice work @TwinFan , is there a testbuild possible? or do you want to release everything together with the next milestone? i could help you test, i fly almost every evening, mostly in europe.

**Comment by Kawo83** [comment]
Hello,
any chance you can upload a preview build ready compiled for xplane?`
I am trying the whole day compile all the stuff myself but given up for now after 10 hours :(

Thanks in advance! Would love testing RealTraffic

**Comment by Kawo83** [comment]
I was able to build it now after hours and hours. Sadly after log entry LiveTraffic 1554049275.0 INFO  Src\LTRealTraffic.cpp:113/SetStatus: RealTraffic network status changed to: Starting... nothing more happens :(

Any clue what i can do to get it connected?

**Comment by TwinFan** [comment]
Documentation is [already prepared in the next-version thread](https://twinfan.gitbook.io/livetraffic/v/v1.10/setup/installation/realtraffic-connectivity).

I respect that you managed to compile the software yourself, but please refrain from discussing compile problems here. The issue isn‘t even closed, so strictly speaking not finalized. My development happens on Mac, porting to Windows is always a second step and necessary in the area of networks. Go back one commit...nothing changed in the RealTraffic area.

**Comment by iParsian** [comment]
> I was able to build it now after hours and hours. Sadly after log entry LiveTraffic 1554049275.0 INFO Src\LTRealTraffic.cpp:113/SetStatus: RealTraffic network status changed to: Starting... nothing more happens :(
> 
> Any clue what i can do to get it connected?
> 
> When trying the newest commit, this line does a error when compiling:
> s.sin_port = (in_port_t)htons(f_port);
> 
> file: network.cpp
> 
> Fehler	C2065	"in_port_t": nichtdeklarierter Bezeichner	LiveTraffic	G:\Downloads\X-Plane\X-Plane 11\Addons\LiveTraffic\31.03.19\livetraffic - Kopie\Src\Network.cpp	316
> 
> Edit: Got it to working, did not know i need a software of them :) Waiting for my licence now.
> Could not compile the latest commit anyways with the above error.

Can I ask you kindly send your compiled version to me, my VS is 2015 and I must upgrade to 2017 at least to be able to compile this (of course if it is alright by author)

**Comment by TwinFan** [comment]
Guys, this is supposed to become part of my implementation documentation, not a chat for keen testers. Please stop that now or change to private channels. I don't want to delete/block you. I will release LiveTraffic in due time. We are talking days, not months.
