### ISSUE TITLE
Generic liveries displayed instead of specific airline ones

### ISSUE THREAD

**Issue by Pastaiolo** [TwinFan/LiveTraffic#68]
**Describe the bug**
I seem to be getting the right plane models in game, but not the right livery. In fact every plane has a generic aircraft type livery even tho from the data the right airline is identified. This seems to be happening everywhere regardless of airport and time of the day.
I tried to search in the info pages because at this point i don't know if it is supposed to display the right livery or not. I apologize in advance if i have understood something wrong.

![cessna_172sp_5](https://user-images.githubusercontent.com/46840548/51425921-3c050980-1be3-11e9-9288-ab1605d89f9c.png)

**Comment by akports103** [comment]
ok this problems seems to only arise when using XCSL, its currently not compatible with xsquawkbox 1.3.3. delete the xcsl pack and replace it with bluebell package.
https://forums.x-plane.org/index.php?/files/file/37041-bluebell-obj8-csl-packages/

**Comment by TwinFan** [comment]
On hold. Pending review after FollowMe Car ships directly with LiveTraffic and X-CSL updater no longer overwrites Bluebell install in `Resources/CSL`.

**Comment by TwinFan** [comment]
With v0.91 installation was changed: FollowMe car ships directly removing the need to start the X-CSL installer, which seems to destroy some bluebell installations.
Closed.
