### ISSUE TITLE
Draw Aircrafts on XP11's map to be used as a kind of Radar

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#78]
**Current Situation / Problem**
Difficult to figure out which aircrafts are around, also see #21.

**Suggested Solution**
Additionally, check out putting the aircrafts into XP11's map. With XP11 the [MAP API](https://developer.x-plane.com/sdk/XPLMMap/) has been greatly extended and should easily be able to cope with it.
This change probable best goes into the multiplayer lib.

**Benefits**
Have an overview of aircrafts. Can serve as kind of a "radar"

**Comment by albar965** [comment]
Is it possible to "inject" aircraft information using the usual XP multiplayer datarefs like `sim/multiplayer/position/planeX_...`?
That way [Liittle Navmap](https://github.com/albar965/littlenavmap) could display the aircraft as AI.
Alternatively we could agree on new datarefs.
Alex

**Comment by MuellerPatrick** [comment]
On my system the LT-planes are visible in the XPlane map and also in littlenavmap. I dont think there is a need of an enhancement, its already there. Maybe forget to set some AI-planes ?

**Comment by albar965** [comment]
Thanks @MuellerPatrick . Great to hear that it is working. @TwinFan : Looking at 86 now.
