### ISSUE TITLE
Rebase multiplayer lib on another fork (like swift's)

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#81]
**Current Situation / Problem**
My multiplayer fork is based on kuroneko's, which might be fairly original, but also unchanged for 2y now. 

**Suggested Solution**
Rebase on another fork: [swift](https://github.com/swift-project/libxplanemp) or [xfs](https://github.com/frungy2/libxplanemp-xfs).

On first compare xfs seems to be a bit ahead at the moment, has e.g. the clamp logic and the taxi light thingy.

**Benefits**
Benefit from all enhancements and fixes already in the newer versions (which still are unchange since Feb 2018), especially

- OBJ8 format allowing for multi-liveries
- clamping, which seems to a way of deriving the lowest point in a model to make it roll on wheels without the need for VERT_OFFSET
- taxi lights (to replace current logic to optionally keep landing lights on during taxi #76) 

**Additional context**
Still need to recreate some stuff:

- default model matching based on Doc8643 aircraft categories and added an additional pass to match airline (part of #44)
- label size becomes unreadable with SSAA antialiasing (verify if needed) (#63)
- different colors for a/c labels (i#53)
- handling of file paths if XPLM_USE_NATIVE_PATHS is enabled (issue #66)
- Get name of plane model

**Comment by kuroneko** [comment]
You could just talk to me.

**Comment by TwinFan** [comment]
With this change further decisions moved out to after v1.0

**Comment by TwinFan** [comment]
All benefits are available by now without basing on another fork. Closed.
