### ISSUE TITLE
No traffic displaying

### ISSUE THREAD

**Issue by tiagocarleial** [TwinFan/LiveTraffic#87]
When it loads and says
filling buffer: seeing 25 aircrafts , 0 displaying , 0 seconds to buffer

cant see any traffic. Anyone solved this issue?

**Comment by TwinFan** [comment]
Not a bug topic, but a support topic better suited for X-Plane.org or Discord channels. Provide your `Log.txt` there so we get something for analysis.
Typical solution in previous cases that started similar was: PC clock was ahead of time, so check your time. FAQ has a topic on [no aircrafts](https://twinfan.gitbook.io/livetraffic/reference/faq#i-dont-see-any-planes-what-can-i-do).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TwinFan** [comment]
No further feedback, closed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
