### ISSUE TITLE
CURL_OPENSSL_4

### ISSUE THREAD

**Issue by stakosm** [TwinFan/LiveTraffic#91]
**Describe the bug**
all the required libraries are installed but gives this error at log.txt
Linux Mint 18.1 

./lin.xpl: /usr/local/lib/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by ./lin.xpl)
./lin.xpl: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./lin.xpl)
./lin.xpl: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./lin.xpl)
	linux-vdso.so.1 =>  (0x00007ffd009d4000)
	libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007f538a5b0000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f538a37f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5389ffd000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5389cf4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5389ade000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5389714000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f538ab47000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f53894e1000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f53892c5000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f538905c000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f5388c17000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f53889cd000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f53887be000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f538856d000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f5388353000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5388136000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f5387e06000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f5387bd3000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f538799d000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f538771d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5387519000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f5387247000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f5387018000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f5386e14000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f5386c09000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f53869ee000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f53867d3000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f5386592000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f538632e000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f538611b000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f5385f17000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f5385d0e000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f5385a84000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f53857e2000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f53855af000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f5385399000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f5385191000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f5384f68000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f5384d59000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f5384b0e000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f5384839000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f5384601000)

**Comment by TwinFan** [comment]
curl comes in variants, and you don't seem to have the one with CURL_OPENSSL_4. But there are also two more dependencies, which are not fulfilled. Unfortunately, I can't help with individual Linux issues as I don't have a Linux environment and definitely one of each flavour.
Only thing I can recommend is asking the guys in [this X-Plane.org forum thread](https://forums.x-plane.org/index.php?/forums/topic/168611-compiling-livetraffic-for-linux/). That was originally about compiling LiveTraffic, but at least Linux guys with more knowledge than me are listening.

**Comment by sparker256** [comment]
I believe that Linux Mint 18.1 is the same as Ubuntu 16.04 and if that is true it will get the same error about Curl.

**Comment by TwinFan** [comment]
Won’t fix. Closed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
