### ISSUE TITLE
Camera near ai aircraft

### ISSUE THREAD

**Issue by kawki** [TwinFan/LiveTraffic#93]
a  camera that follows ai aircraft is strongly needed.
Thanks

**Comment by TwinFan** [comment]
Well...“strongly needed“ might maybe not be my personal priority...but in fact this function is not terribly difficult to implement. See [XPLMCamera](url
https://developer.x-plane.com/sdk/XPLMCamera/). We just need:

- [ ] Button in a/c info wnd to start the camera view
- [ ] When pressed call XPLMControlCamera providing a callback function to provide the position
- [ ] The callback function just needs to return OpenGL-converted coordinates of the plane. To actually also see the plane we‘d need to adjust the coordinates a bit backward and up (which might be the most difficult part: Where is ‚back‘ in the OpenGL coordinate system? That depends on the plane’s heading. We can do these Calc already in World coordinates, though. ‚Up‘ is simple.)

**Comment by TwinFan** [comment]
Also had to add parameters to the flight model file as the camera offset (compared to reported plane position) certainly differs with plane size.
Looks pretty cool now...but the models are shaking, especially when moving fast. The camera stays steady, scenery moves steadily around the camera, i.e. position calculation is smooth. But the model in front of the camera shakes. With position updating smoothly this can only be an issue with placing the model in 3D space, meaning a problem with libxplanemp. Might be a rounding issue somewhere, or some OpenGL drawing artefact. That's not my area of expertise...but I keep this issue open as a reminder for the moment.
