### ISSUE TITLE
Step-by-step instruction for Bluebell packages (was: No aircraft appearing, only labels)

### ISSUE THREAD

**Issue by seeingeyegod** [TwinFan/LiveTraffic#98]
**Describe the bug**
A clear and concise description of what the bug is: What's wrong?

I am pretty sure I have the aircraft packages installed correctly, though I could be wrong. But I only see labels flying around, taxiing, landing, etc. No models. I turned on debugging and have the log.txt, I hope you can tell what is happening.

**To Reproduce**
1. go to a populated airport anywhere in the world
2. Fly and notice that there are a bunch of labels of live aircraft flying around, but no models EXCEPT the car/SUV  vehicle is working actually..
[Log.txt](https://github.com/TwinFan/LiveTraffic/files/2849484/Log.txt)

Reproducing issues with the modelling/display of live aircrafts is next to impossible. Remember, that LiveTraffic relies on live flight data from various public sources. They aren't accurate to the feet. If, however, you observe a behaviour more or less repeatedly when 'watching' live data then provide:
1. Location (preferably airport, coordinates otherwise)
2. Weekday / Time of day (scheduled flights tend to repeat at least weekly)
3. additional pattern like aircraft type, heading, altitude, flight phase...
4. A Log.txt file with log level (Settings/Advanced) set to 'Debug'

**Expected behavior**
For traffic to appear as described in app description

**Screenshots**
![cirrussf50_33](https://user-images.githubusercontent.com/18638797/52540790-6fe6d100-2d42-11e9-861d-378410a441a4.png)
![cirrussf50_30](https://user-images.githubusercontent.com/18638797/52540795-7bd29300-2d42-11e9-8dff-296a246b128f.png)
![cirrussf50_32](https://user-images.githubusercontent.com/18638797/52540803-8ab94580-2d42-11e9-8304-51961012d96c.png)

**Technical Info:**
 - OS: [Mac/Win/Linux] Windows 8.1
 - X-Plane version: 11.30 
 - LiveTraffic version: v0.92

**Log.txt**
Attach your Log.txt file, if reproducible then please reproduce with log level (Settings/Advanced) set to 'Debug' first.

**Comment by seeingeyegod** [comment]
Reading this: https://twinfan.gitbook.io/livetraffic/setup/other-multiplayer-in-parallel
and looking in the log file it seems like I probably have a conflict with another plugin so I'm going to look into that, this is hopefully something easy to fix. (probably my fault)

**Comment by seeingeyegod** [comment]
oh shit... think i know what i screwed up, lol. Maybe this will help someone if I'm right.

**Comment by seeingeyegod** [comment]
So when I went to download the CSL package, I read: 
"This is a new CSL package for XSquawkBox and potentially other X-Plane pilot clients."
I didn't notice the instruction about ignoring this and copying the CSL into livetraffics plugin directory, I thought I needed to install squawkbox as well to install the CSLs, and copy them into it's plugin directory. Squawkbox was actually totally unnecessary I see now. Figured out my mistake, traffic models are working now. Delete this thread if need be.

**Comment by TwinFan** [comment]
The validation step in the CSL Installation procedure as well as step 5 of the [FAQ on missing planes](
https://twinfan.gitbook.io/livetraffic/reference/faq#i-dont-see-any-planes-what-can-i-do) should have covered you.

As an immediate action I have specifically added the case of labels but now planes as step 6 in above FAQ.

I take this issue as a reminder for something I had planned anyway: Step-by-step instructions for installing the Bluebell models, ie. a documentation enhancement.

**Comment by TwinFan** [comment]
Step-by-step instructions available:
https://twinfan.gitbook.io/livetraffic/setup/installation/step-by-step
